version: '3.8'

services:
    web:
        container_name: web
        build: .
        ports:
            - 8080:8080
        privileged: true
        volumes:
            - ./code:/usr/src/app
        tty: true
        stdin_open: true
        command: /bin/sh